Pintushi\Bundle\UserBundle\Entity\User:
    collectionOperations:
           post:
               denormalization_context:
                   groups: ["write"]
               validation_groups: ["pintushi", "add_user"]
               access_control: is_granted('pintushi_user_create')
           get:
               access_control: is_granted('pintushi_user_view')
               acl_enabled: true
    itemOperations:
           put:
               denormalization_context:
                   groups: ["write"]
               validation_groups: ["pintushi"]
               access_control: is_granted('pintushi_user_edit', object)
           get:
               access_control: is_granted('pintushi_user_view', object)
           delete:
               access_control: is_granted('pintushi_user_delete', object)
           get_user_profile:
              route_name: "api_user_profile"
    attributes:
        normalization_context:
             groups: ["read"]
        denormalization_context:
           groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin

Pintushi\Bundle\UserBundle\Request\UpdateUserProfile:
    collectionOperations:
        post:
            route_name: 'api_admin_update_user_profile'
    itemOperations: {}
    attributes:
        normalization_context:
            groups: ["read"]
            enable_max_depth: true
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin


Pintushi\Bundle\UserBundle\Request\ChangePhoneNumber:
    collectionOperations:
        post:
            route_name: 'api_admin_update_user_profile'
    itemOperations: {}
    attributes:
        normalization_context:
            groups: ["read"]
            enable_max_depth: true
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
        route_prefix: /admin

Pintushi\Bundle\UserBundle\Request\ResetPassword:
    collectionOperations:
            post:
                route_name: 'api_admin_reset_password'
    itemOperations: {}
    attributes:
        normalization_context:
            groups: ["read"]
            enable_max_depth: true
        denormalization_context:
            groups: ["write"]
        validation_groups:  ["pintushi"]
