Pintushi\Bundle\UserBundle\Request\UpdateUserProfile:
    attributes:
        firstName:
            groups: ['write']
        lastName:
            groups: ['write']
        avatar:
            groups: ['write']
