navigation:
    menu_config:
        items:
            users_management:
                label:    '用户管理'
                uri:      '#'
                position: 20
            user_list:
                label:    '用户'
                position: 10
            user_roles:
                label:    '角色'
                position: 20
            user_groups:
                label:    '组'
                position: 30
        tree:
            application_menu:
                children:
                    user_manage:
                        children:
                            user_list: ~
                            user_roles: ~
                            user_groups: ~
