api:
    resources:
        Pintushi\Bundle\UserBundle\Entity\User:
            scope: pintushi_user
            normalization_context:
                groups: ['User', 'Organization', 'BusinessUnit']
            route_prefix: /admin
            validation_groups: ['pintushi']
            form: 'Pintushi\Bundle\UserBundle\Form\Type\UserType'
            repository_class: 'Pintushi\Bundle\UserBundle\Repository\UserRepository'
            operations:
                create:
                    action: create
                    path: '/users'
                    validation_groups: ['pintushi', 'pintushi_user_create']
                    access_control: is_granted('pintushi_user_user_create')
                create_form:
                    action: create
                    path: '/users/create-form'
                    methods: ['GET']
                    validation_groups: ['pintushi', 'pintushi_user_create']
                    access_control: is_granted('pintushi_user_user_create')
                delete:
                    action: delete
                    access_control: is_granted('pintushi_user_user_delete', object)
                update:
                    action: update
                    path: '/users/{id}'
                    access_control: is_granted('pintushi_user_user_edit', object)
                    requirements:
                        id: '\d+'
                update_form:
                    action: update
                    path: '/users/{id}/update-form'
                    methods: ['GET']
                    access_control: is_granted('pintushi_user_user_edit', object)
                    requirements:
                        id: '\d+'
                view:
                    action: view
                    access_control: is_granted('pintushi_user_user_view')
                get_user_profile:
                    action: view
                    path: '/profile'
                    resource_provider: "expr:service('pintushi_security.token_accessor').getUser()"
                update_user_profile:
                    action: update
                    path: '/profile'
                    form: 'Pintushi\Bundle\UserBundle\Form\Type\UserProfileType'
                    resource_provider: "expr:service('pintushi_security.token_accessor').getUser()"
                update_user_profile_form:
                    action: update
                    methods: ['GET']
                    path: '/profile-form'
                    form: 'Pintushi\Bundle\UserBundle\Form\Type\UserProfileType'
                    resource_provider: "expr:service('pintushi_security.token_accessor').getUser()"
                index:
                    action: index
                    grid: 'user-grid'
                    normalization_context:
                        groups: ['User', 'Default', 'Organization']
                    access_control: is_granted('pintushi_user_user_view')
