Pintushi\Bundle\UserBundle\Entity\User:
    exclusion_policy: ALL
    xml_root_name: user
    properties:
        groups:
            expose: true
            type: array
            xml_attribute: true
            groups: [Group]
