Pintushi\Bundle\UserBundle\Request\ResetPassword:
    constraints:
    -   Pintushi\ShopApiPlugin\Validator\Constraints\SmsCaptcha:
            codeField: code
            groups: [pintushi]
            phoneNumberField: phoneNumber
    properties:
        code:
          - NotBlank: { groups: ["pintushi"] }
        password:
          - NotBlank: { groups: ["pintushi"] }
          - Rollerworks\Component\PasswordStrength\Validator\Constraints\PasswordStrength:
                minLength: 6
                minStrength: 3
                groups: ["pintushi"]
                message: "至少6个字符，且需包括大小写，特殊字符"
